import { mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

/**
 * User rc files often rebuild PATH from scratch, wiping env-var injection.
 * So for zsh we point ZDOTDIR at a generated bootstrap dir that sources the
 * user's real dotfiles first, then re-prepends the airun9 bin dir — the
 * last word on PATH is ours, and the user's dotfiles are never touched.
 */

const ZDOTDIR = join(homedir(), '.airun9', 'zdotdir')

const HEADER =
  '# Generated by AIRUN9 on every app start — do not edit.\n' +
  '# Sources your real zsh config, then re-adds the airun9 tools to PATH.\n'

const sourceUserFile = (name: string): string =>
  `_airun9_user_zdotdir="\${AIRUN9_USER_ZDOTDIR:-$HOME}"\n` +
  `[ -f "$_airun9_user_zdotdir/${name}" ] && . "$_airun9_user_zdotdir/${name}"\n`

const FILES: Record<string, string> = {
  '.zshenv': HEADER + sourceUserFile('.zshenv'),
  '.zprofile': HEADER + sourceUserFile('.zprofile'),
  '.zlogin': HEADER + sourceUserFile('.zlogin'),
  '.zshrc':
    HEADER +
    sourceUserFile('.zshrc') +
    `
# Re-prepend after the user rc ran, so PATH rebuilds cannot drop our tools
if [ -n "$AIRUN9_BIN" ]; then
  case ":$PATH:" in
    *":$AIRUN9_BIN:"*) ;;
    *) export PATH="$AIRUN9_BIN:$PATH" ;;
  esac
fi

# /etc/zshrc defaults HISTFILE under ZDOTDIR; keep history where it always was
[ "$HISTFILE" = "$ZDOTDIR/.zsh_history" ] && HISTFILE="$HOME/.zsh_history"
`
}

/** Write the bootstrap files (idempotent) and return env vars for the PTY */
export function zshBootstrapEnv(binDir: string): Record<string, string> {
  const shell = process.env.SHELL ?? ''
  if (!shell.includes('zsh')) return {}

  mkdirSync(ZDOTDIR, { recursive: true, mode: 0o700 })
  for (const [name, content] of Object.entries(FILES)) {
    writeFileSync(join(ZDOTDIR, name), content, { mode: 0o600 })
  }

  return {
    ZDOTDIR,
    AIRUN9_USER_ZDOTDIR: process.env.ZDOTDIR ?? homedir(),
    AIRUN9_BIN: binDir
  }
}
